AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  Application1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Statemachine-test-lambda-function-1
      Runtime: python3.12
      CodeUri: application_1/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole

  Application2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Statemachine-test-lambda-function-2
      Runtime: python3.12
      CodeUri: application_2/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole

  StarterApplication:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Statemachine-test-lambda-function-starter
      Runtime: python3.12
      CodeUri: starter/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
  

  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: Statemachine-test
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionUri: statemachine/statemachineTemplate.asl.json
      DefinitionSubstitutions:
        StarterFunction: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Statemachine-test-lambda-function-starter
        Application1: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Statemachine-test-lambda-function-1
        Application2: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:Statemachine-test-lambda-function-2

  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole

      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'
